// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service_registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceInstance message definition for gRPC
type GrpcServiceInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	HealthPath    string                 `protobuf:"bytes,6,opt,name=healthPath,proto3" json:"healthPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcServiceInstance) Reset() {
	*x = GrpcServiceInstance{}
	mi := &file_service_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcServiceInstance) ProtoMessage() {}

func (x *GrpcServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_service_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcServiceInstance.ProtoReflect.Descriptor instead.
func (*GrpcServiceInstance) Descriptor() ([]byte, []int) {
	return file_service_registry_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcServiceInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GrpcServiceInstance) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GrpcServiceInstance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GrpcServiceInstance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GrpcServiceInstance) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GrpcServiceInstance) GetHealthPath() string {
	if x != nil {
		return x.HealthPath
	}
	return ""
}

// Request message for GetHealthyServices
type GetHealthyServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthyServicesRequest) Reset() {
	*x = GetHealthyServicesRequest{}
	mi := &file_service_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthyServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthyServicesRequest) ProtoMessage() {}

func (x *GetHealthyServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthyServicesRequest.ProtoReflect.Descriptor instead.
func (*GetHealthyServicesRequest) Descriptor() ([]byte, []int) {
	return file_service_registry_proto_rawDescGZIP(), []int{1}
}

// Response message for GetHealthyServices
type GetHealthyServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*GrpcServiceInstance `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthyServicesResponse) Reset() {
	*x = GetHealthyServicesResponse{}
	mi := &file_service_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthyServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthyServicesResponse) ProtoMessage() {}

func (x *GetHealthyServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthyServicesResponse.ProtoReflect.Descriptor instead.
func (*GetHealthyServicesResponse) Descriptor() ([]byte, []int) {
	return file_service_registry_proto_rawDescGZIP(), []int{2}
}

func (x *GetHealthyServicesResponse) GetServices() []*GrpcServiceInstance {
	if x != nil {
		return x.Services
	}
	return nil
}

// Request message for RegisterService
type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *GrpcServiceInstance   `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_service_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_service_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterServiceRequest) GetInstance() *GrpcServiceInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// Request message for DeregisterService
type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_service_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_service_registry_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterServiceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Request message for SendHeartbeat
type SendHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendHeartbeatRequest) Reset() {
	*x = SendHeartbeatRequest{}
	mi := &file_service_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatRequest) ProtoMessage() {}

func (x *SendHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*SendHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_service_registry_proto_rawDescGZIP(), []int{5}
}

func (x *SendHeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Response message for registration, deregistration, heartbeat (empty)
type ServiceRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Indicate success/failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Optional: provide more details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistryResponse) Reset() {
	*x = ServiceRegistryResponse{}
	mi := &file_service_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistryResponse) ProtoMessage() {}

func (x *ServiceRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistryResponse.ProtoReflect.Descriptor instead.
func (*ServiceRegistryResponse) Descriptor() ([]byte, []int) {
	return file_service_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceRegistryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceRegistryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_registry_proto protoreflect.FileDescriptor

const file_service_registry_proto_rawDesc = "" +
	"\n" +
	"\x16service_registry.proto\x12\x0fserviceregistry\"\xa1\x01\n" +
	"\x13GrpcServiceInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"healthPath\x18\x06 \x01(\tR\n" +
	"healthPath\"\x1b\n" +
	"\x19GetHealthyServicesRequest\"^\n" +
	"\x1aGetHealthyServicesResponse\x12@\n" +
	"\bservices\x18\x01 \x03(\v2$.serviceregistry.GrpcServiceInstanceR\bservices\"Z\n" +
	"\x16RegisterServiceRequest\x12@\n" +
	"\binstance\x18\x01 \x01(\v2$.serviceregistry.GrpcServiceInstanceR\binstance\":\n" +
	"\x18DeregisterServiceRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\"6\n" +
	"\x14SendHeartbeatRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\"M\n" +
	"\x17ServiceRegistryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb2\x03\n" +
	"\x0fServiceRegistry\x12m\n" +
	"\x12GetHealthyServices\x12*.serviceregistry.GetHealthyServicesRequest\x1a+.serviceregistry.GetHealthyServicesResponse\x12d\n" +
	"\x0fRegisterService\x12'.serviceregistry.RegisterServiceRequest\x1a(.serviceregistry.ServiceRegistryResponse\x12h\n" +
	"\x11DeregisterService\x12).serviceregistry.DeregisterServiceRequest\x1a(.serviceregistry.ServiceRegistryResponse\x12`\n" +
	"\rSendHeartbeat\x12%.serviceregistry.SendHeartbeatRequest\x1a(.serviceregistry.ServiceRegistryResponseBw\n" +
	" com.example.serviceregistry.grpcB\x14ServiceRegistryProtoP\x01Z;github.com/lokeshllkumar/load-balancer/internal/proto;protob\x06proto3"

var (
	file_service_registry_proto_rawDescOnce sync.Once
	file_service_registry_proto_rawDescData []byte
)

func file_service_registry_proto_rawDescGZIP() []byte {
	file_service_registry_proto_rawDescOnce.Do(func() {
		file_service_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_registry_proto_rawDesc), len(file_service_registry_proto_rawDesc)))
	})
	return file_service_registry_proto_rawDescData
}

var file_service_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_registry_proto_goTypes = []any{
	(*GrpcServiceInstance)(nil),        // 0: serviceregistry.GrpcServiceInstance
	(*GetHealthyServicesRequest)(nil),  // 1: serviceregistry.GetHealthyServicesRequest
	(*GetHealthyServicesResponse)(nil), // 2: serviceregistry.GetHealthyServicesResponse
	(*RegisterServiceRequest)(nil),     // 3: serviceregistry.RegisterServiceRequest
	(*DeregisterServiceRequest)(nil),   // 4: serviceregistry.DeregisterServiceRequest
	(*SendHeartbeatRequest)(nil),       // 5: serviceregistry.SendHeartbeatRequest
	(*ServiceRegistryResponse)(nil),    // 6: serviceregistry.ServiceRegistryResponse
}
var file_service_registry_proto_depIdxs = []int32{
	0, // 0: serviceregistry.GetHealthyServicesResponse.services:type_name -> serviceregistry.GrpcServiceInstance
	0, // 1: serviceregistry.RegisterServiceRequest.instance:type_name -> serviceregistry.GrpcServiceInstance
	1, // 2: serviceregistry.ServiceRegistry.GetHealthyServices:input_type -> serviceregistry.GetHealthyServicesRequest
	3, // 3: serviceregistry.ServiceRegistry.RegisterService:input_type -> serviceregistry.RegisterServiceRequest
	4, // 4: serviceregistry.ServiceRegistry.DeregisterService:input_type -> serviceregistry.DeregisterServiceRequest
	5, // 5: serviceregistry.ServiceRegistry.SendHeartbeat:input_type -> serviceregistry.SendHeartbeatRequest
	2, // 6: serviceregistry.ServiceRegistry.GetHealthyServices:output_type -> serviceregistry.GetHealthyServicesResponse
	6, // 7: serviceregistry.ServiceRegistry.RegisterService:output_type -> serviceregistry.ServiceRegistryResponse
	6, // 8: serviceregistry.ServiceRegistry.DeregisterService:output_type -> serviceregistry.ServiceRegistryResponse
	6, // 9: serviceregistry.ServiceRegistry.SendHeartbeat:output_type -> serviceregistry.ServiceRegistryResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_registry_proto_init() }
func file_service_registry_proto_init() {
	if File_service_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_registry_proto_rawDesc), len(file_service_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_registry_proto_goTypes,
		DependencyIndexes: file_service_registry_proto_depIdxs,
		MessageInfos:      file_service_registry_proto_msgTypes,
	}.Build()
	File_service_registry_proto = out.File
	file_service_registry_proto_goTypes = nil
	file_service_registry_proto_depIdxs = nil
}
